export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const FETCH_RESTAURANTS_FAILED = 'FETCH_RESTAURANTS_FAILED';
